allowBuilds:
  '@parcel/watcher': false
minimumReleaseAgeExclude:
  - postcss@8.5.25
  - swiper@14.0.7
  - cssnano-preset-default@8.0.5
  - cssnano-utils@6.0.3
  - cssnano@8.0.5
  - postcss-colormin@8.0.3
  - postcss-convert-values@8.0.3
  - postcss-discard-comments@8.0.3
  - postcss-discard-duplicates@8.0.3
  - postcss-discard-empty@8.0.3
  - postcss-discard-overridden@8.0.3
  - postcss-merge-longhand@8.0.3
  - postcss-merge-rules@8.0.3
  - postcss-minify-font-values@8.0.3
  - postcss-minify-gradients@8.0.3
  - postcss-minify-params@8.0.3
  - postcss-minify-selectors@8.0.4
  - postcss-normalize-charset@8.0.3
  - postcss-normalize-display-values@8.0.3
  - postcss-normalize-positions@8.0.3
  - postcss-normalize-repeat-style@8.0.3
  - postcss-normalize-string@8.0.3
  - postcss-normalize-timing-functions@8.0.3
  - postcss-normalize-unicode@8.0.3
  - postcss-normalize-url@8.0.3
  - postcss-normalize-whitespace@8.0.3
  - postcss-ordered-values@8.0.3
  - postcss-reduce-initial@8.0.3
  - postcss-reduce-transforms@8.0.3
  - postcss-svgo@8.0.4
  - postcss-unique-selectors@8.0.3
  - stylehacks@8.0.3
